### ISSUE TITLE
Deal with Wolfram video type

### ISSUE THREAD

**Issue by light-matters** [scicloj/wolframite#115]
Currently, Wolframite spits back a list of video options (A form) instead of the actual video stream.

We should learn how to pipe this through to other functions seamlessly. Can take inspiration from how tools.hiccup.view is implemented?

```clojure
(Video /home/ctw/Documents/Wolfram/Video/VideoTrim-2024-09-14T12-07-28.mp4 (-> Appearance Automatic) (-> AudioOutputDevice Automatic) (-> AudioTrackSelection []) (-> PlaybackSettings {}) (-> SoundVolume Automatic) (-> SubtitleTrackSelection []) (-> VideoTrackSelection [1]))
```

Marked this as a bug and an enhancement because it's important missing functionality.

**Comment by holyjak** [comment]
See https://github.com/scicloj/wolframite/pull/131

**Comment by holyjak** [comment]
@light-matters is this a duplicate of https://github.com/scicloj/wolframite/issues/118 or what?

**Comment by light-matters** [comment]
must be

**Comment by light-matters** [comment]
Duplicate of #118 

(even though it's older :) )
