### ISSUE TITLE
Consider promoting help! into the core ns

### ISSUE THREAD

**Issue by holyjak** [scicloj/wolframite#130]
Help seems rather useful in daily work, why hide it in an obscure ns? Let's `wolframite.lib.helpers/help! -> wolframite.core/help!` !

**Comment by light-matters** [comment]
Good idea.

**Comment by light-matters** [comment]
The more I think about it, the more I prefer the idea of a separate api namespace. 'core' is just not very descriptive and combines many unrelated things. Putting everything in there that is 'useful' to the user is not scalable. 

I will make a PR and then you can critique it!

**Comment by holyjak** [comment]
Help! itself added by https://github.com/scicloj/wolframite/pull/132, but not the other suggestions.

**Comment by light-matters** [comment]
`??` was added in #132, but it's not so useful because of all of the Mathematica-specific styling options. I'm closing for now.
