### ISSUE TITLE
Using Wolfram Language with WolframAlpha, without a local Wolfram/Mathematica installation

### ISSUE THREAD

**Issue by fleimgruber** [scicloj/wolframite#16]
This is to keep track of usage without a local Mathematica installation as mentioned in https://github.com/scicloj/Clojuratica#dependencies.

A common use case would be to just use WolframAlpha queries as shown in https://www.youtube.com/watch?v=DqoUeFOSNjQ. It would be nice to be able to include `clojuratica` in the user deps.edn and then be able to interact with WolframAlpha already to get a taste.

**Comment by holyjak** [comment]
Won't fix, we do not have the resources. But will keep it in mind as an option...
