### ISSUE TITLE
Update tests

### ISSUE THREAD

**Issue by metasoarous** [scicloj/wolframite#2]
There are some tests in `src/clojuratica/test`, but these probably no longer work after our initial refactor (see: #1). We should review these, and get them back in shape.

**Comment by qazwsxpawel** [comment]
As a first step I moved the `test` directory to the top level.

I would also try to get  some test notebooks from Wolfram's people.

**Comment by holyjak** [comment]
No need for this issue. We are well aware of the need, and plan to work on it.
