### ISSUE TITLE
lazy intern on the demo

### ISSUE THREAD

**Issue by daslu** [scicloj/wolframite#27]
At the `demo` namespace:
https://github.com/scicloj/wolframite/blob/43a075c6ceac29762ad7693c40e049706404ee64/dev/demo.clj#L86

`(map wl/clj-intern ['Dot 'Plus])` is lazy.

So, if one loads the whole namespace, it does not actually intern anything, and the forms relying on `Dot` and `Plus` fail.

Replacing `map` with `run!` or `mapv` will fix this.

**Comment by holyjak** [comment]
Thank you!

BTW beware that in https://github.com/scicloj/wolframite/pull/26 I am reworking load-all-syms. so that it still loads them, but does not turn them into executable functions (i.e. you still need wl/eval on the reult). Will update docs and namespaces too.

**Comment by daslu** [comment]
Thanks!
