### ISSUE TITLE
Make sure that default jlink & kernel initialization work for non-Mathematica Wolfram Language installs

### ISSUE THREAD

**Issue by metasoarous** [scicloj/wolframite#3]
We've created `src/clojuratica/jlink.clj` and `src/clojuratica/init.clj` to automate some of the process of connecting to the JLink code and Kernel initialization processes respectively. However, the paths (mostly in the `jlink.clj` file) were based on a Mathematica installation. It's unclear whether these relative paths will be the same for a non-Mathematica Wolfram Language installation. We should verify this if possible, and make any necessary adjustments.

**Comment by holyjak** [comment]
Addressed by #14 Works fine for Wolfram Engine installation.
