### ISSUE TITLE
Replace hand-rolled HashMap type with new WL "Associations"

### ISSUE THREAD

**Issue by metasoarous** [scicloj/wolframite#4]
At the time of writing, Mathematica didn't have an associative hash-map type data structure, but does now have "Associations". As mentioned by one of the more recent contributors to Clojuratica, we should adapt the extant mappings to translate Clojure maps to these Association structures for better semantic mirroring between the languages.

**Comment by holyjak** [comment]
Addressed by #14 I believe?
