### ISSUE TITLE
User-defined aliasing

### ISSUE THREAD

**Issue by light-matters** [scicloj/wolframite#47]
Currently, aliases can be supplied by adding pairs to the relevant maps in wolframite.runtime.defaults, but this is not exposed to consumers of the wolframite library.

A first step would be making this available via a function call, probably at the point of explicit initialization (coming soon!).

**Comment by light-matters** [comment]
A thought that occurred to me is that long-standing shortcuts like this could potentially be put in a wolfram package directly, as done already in the core namespace:

```clojure
...
(wl-eval-conv '(Needs "Parallel`Developer`"))
...
```

I don't know if this would have any performance benefits. It's still not a solution for user-defined aliases in any case though.

**Comment by holyjak** [comment]
# Already possible

You can already do this:

```clojure
(wl/init! {:aliases '{** Power}})
(wl/eval '(** 2 5)) ; => 32
```


```clojure
(wl/init!)
(wl/eval '(** 2 5) {:aliases '{** Power}}) ; => 32
```

I suggest we add info about this to the docs and then close this issue - and possibly make a new one for more powerful aliases. (Such as the experimental fn aliases explored in #58. WDYT, @light-matters ?

**Comment by light-matters** [comment]
Great, I like your thinking. I was about to open an issue about having two (multiple?) wolfram.clj files: one which is just simply the wolfram definitions and functions and an 'extended' one which has lots of usability definitions.

**Comment by light-matters** [comment]
I've added a 'Customizing Wolframite' section to the doc (the latest PR).
