### ISSUE TITLE
JLink detection still unstable

### ISSUE THREAD

**Issue by light-matters** [scicloj/wolframite#49]
Tried to use Wolframite on another machine (Still linux, Manjaro, but Mathematica version 13.0) and ran into more JLink path problems. Not sure why Wolfram has so many default paths...

This time, there is an extra subdirectory in the path which breaks the absolute path constructor. 

We should probably move to using a more intelligent system, i.e. to programmatically 'search' for the binaries, at least as a backup when the default paths don't work.

**Comment by light-matters** [comment]
Made a quick fix for this particular problem, 06ef8f2, but the jlink namespace still needs tidied up.

**Comment by light-matters** [comment]
Tided up the jlink namespace and restructured the functions, df1f6aaeffc8dd42ddd6b81b24f81de497f11bbd, but would still be nice to have a backup 'search'.

**Comment by light-matters** [comment]
Searching for the binaries/jlink as a last resort is now implemented (f617013).

**Comment by light-matters** [comment]
Reopened, because jlink is not automatically detected in Mathematica installations with version paths, as opposed to the relevant kernels. This is because the version path correction is not done at the (defn info...) level, but only at the (defn path--kernel...) function.

**Comment by holyjak** [comment]
@light-matters looking at the code, this seems to be fixed now. Could you be so kind and confirm?
