### ISSUE TITLE
Update the SciClojs Wolframite site for v1

### ISSUE THREAD

**Issue by holyjak** [scicloj/wolframite#57]
The https://scicloj.github.io/wolframite/ page points to a page about the old Clojuratica project. We want the new site for Wolframite v1 to be there - and to build in in accordance with how SciCloj wants its site to be built.

@daslu I guess you have some input how best we can bundle our docs for inclusion in the SciCloj website so that it fits well and is consistent with the look&feel of the site?

**Comment by daslu** [comment]
@holyjak It is a good idea to consider this kind of consistency in look & feel.

Most Scicloj libraries nowadays are documented either as a [Quarto](https://quarto.org/) book (e.g., [Kindly](https://scicloj.github.io/kindly-noted/)) or as a single-page Quarto notebook (e.g., [Tablecloth](https://scicloj.github.io/tablecloth/)).

If this sounds like a good option, I'd be glad to propose a pull request for such a setup (using https://scicloj.github.io/clay/).

For now, this is not consistent with the Scicloj website itself. Hopefully, one day, we will convert the website to a Quarto setup for better harmony.

**Comment by holyjak** [comment]
Thank you! We would like to have multiple pages, as aside of the readme and the demo namespace(s), we will also have couple of tutorials. Any help is most appreciated!

**Comment by holyjak** [comment]
Fixed by https://github.com/scicloj/wolframite/pull/67 and updating the repo's GH Pages config to read from main/docs
