### ISSUE TITLE
outdated orchard dev dependency

### ISSUE THREAD

**Issue by daslu** [scicloj/wolframite#70]
The `:dev` alias at `deps.edn` has a few outdated dependencies.

One of them is `cider/orchard`:
https://github.com/scicloj/wolframite/blob/8510c7e/deps.edn#L12

```clj
                              cider/orchard {:mvn/version "0.7.3"}
```

Probably, it is not necessary anymore. Anyway, it is an old version of this library, which seems to conflict with the current version of `cider-nrepl.`

**Comment by holyjak** [comment]
pls feel free to send a PR!

**Comment by holyjak** [comment]
Otheriwse, I will try to remember to remove it next time I am around the code.

**Comment by daslu** [comment]
Here, thanks:
https://github.com/scicloj/wolframite/pull/73
