### ISSUE TITLE
Wolfram rules converted to form that is no longer supported (Edit: Renamed the issue as the source is quite a different problem)

### ISSUE THREAD

**Issue by light-matters** [scicloj/wolframite#76]
As [described below](https://github.com/scicloj/wolframite/issues/76#issuecomment-2239388345),

The minimum example of failure is

(wl/eval (wl/eval (w/-> 'x 5)))

Somehow turning [Wolfram Rules](https://reference.wolfram.com/language/howto/CreateAndUseRules.html) into (-> ...) works but the other way doesn't anymore.

_Aside: Can we add a practical example of leveraging rules to the docs/demo?_

----

### Origina description

Load for-scientists.cavity-physics namespace and try building the html. The same namespace works fine using the wolframite-examples project (where wolframite is imported as a library). 

Fails with the falling error:
```
1. Unhandled java.lang.IllegalArgumentException
   No matching ctor found for class com.wolfram.jlink.Expr

            Reflector.java:  337  clojure.lang.Reflector/invokeConstructor
      jlink_proto_impl.clj:   43  wolframite.impl.jlink-proto-impl.JLinkImpl/expr
               convert.clj:   98  wolframite.base.convert/eval17569/fn
              MultiFn.java:  234  clojure.lang.MultiFn/invoke
               convert.clj:  146  wolframite.base.convert/eval17620/fn/fn
                  core.clj: 2772  clojure.core/map/fn
```

**Comment by light-matters** [comment]
It makes no sense, but it stops working at commit  c50267a89a1f9dd50eef56081b73df15ce81ffa4

It works at commit 6e209fa13f569c32e62a0f5a19d67a1af92c2e7e

**Comment by light-matters** [comment]
It seems to be something to do with the double eval.

**Comment by light-matters** [comment]
The minimum example of failure is actually
```clojure
(wl/eval (wl/eval (w/-> 'x 5)))
```
Somehow turning Wolfram rules into (-> ...) works but the other way doesn't anymore.

**Comment by light-matters** [comment]
Either we should resupport aliasing -> to Rule or w/-> should evaluate to 'Rule'.

**Comment by holyjak** [comment]
Well, `base-aliases` do contain `'->   'Rule` so I am not sure that aliasing is the core problem here.

**Comment by holyjak** [comment]
Not sure what eactly is going on here, but the exception is thrown on the second eval, when we try to turn `5` into an expr using `(Expr. 5)` - which fails b/c 5 here is Integer, not int, i.e. not primitive.

**Comment by light-matters** [comment]
good find
