### ISSUE TITLE
Make initialization step explicit

### ISSUE THREAD

**Issue by metasoarous** [scicloj/wolframite#8]
Both @qazwsxpawel and I feel somewhat icky about the use of side-effecting namespaces, like `clojuratica.init`, so I'm wondering if we shouldn't just have the call to `init!` be an explicit part of the api that gets called before you can start using Clojuratica?

This issue is somewhat related to #7, since it bears on where we locate these pieces.

# Impl. notes

* Make it trivial to extend / override the built-in "aliases" (such as * -> Times)

**Comment by holyjak** [comment]
WDYT @light-matters ? This would make sense to me as well.
