### ISSUE TITLE
load-package! (or alias) not available from core.clj

### ISSUE THREAD

**Issue by light-matters** [scicloj/wolframite#87]
Currently, core.clj is the defactor entry-point for Wolframite. Unfortunately however, exposing load-package! here is not straightforward because of circular dependencies.

If we want load-package! to be exposed in core then we either
1.  copy across the whole namespace
2. find a way to use 'eval' without referring to core
3. create a separate API namespace that exposes the key Wolframite functions

What do we think @holyjak ?

**Comment by holyjak** [comment]
IS this addressed sufficiently by https://github.com/scicloj/wolframite/pull/84#issuecomment-2248900974 ?
