### ISSUE TITLE
Add clj-kondo configuration

### ISSUE THREAD

**Issue by metasoarous** [scicloj/wolframite#9]
Relevant clj-kondo documentation for getting these installed as part of the project:

https://github.com/clj-kondo/clj-kondo/blob/master/doc/config.md#exporting-and-importing-configuration

This would help:
* Clojuratica+clj-kondo users (ideally) get more helpful warning/error messages
  * ... or at _least_ fewer spurious error messages coming out of the main `WL` macro
* Us maintain the codebase internals, thanks to all of the somewhat wild macros that make up the implementation (see especially the `clojuratica.lib.options` macros).

**Comment by metasoarous** [comment]
Some relevant bits of information from borkdude regarding different approaches to handling macros: https://github.com/clj-kondo/clj-kondo/issues/1443

**Comment by qazwsxpawel** [comment]
For the `WL` macro I've suggested ignoring `:unresolved-symbol`. 
For some other things `:lint-as` would be handy but I don't know any macro with similar structure. 
I guess that means we will need to look into hooks?

**Comment by holyjak** [comment]
Addressed by #14
