### ISSUE TITLE
add internal explanatory references, e.g. raw vs evaluated forms

### ISSUE THREAD

**Issue by light-matters** [scicloj/wolframite#98]
@holyjak  said:
_Perhaps the Quickstart should be even more clear on the distinction between the "quoted / unevaluated data form" like '(Power 2 3) and the "convenience function form" of (wl/Power 2 3) (and the fact that the latter is only a thin layer over the former). Then we could also refer to that section..._

**Comment by holyjak** [comment]
Likely we need first https://github.com/scicloj/wolframite/issues/97 to have something to link to
